<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net462;net472;net6.0;net8.0;net10.0</TargetFrameworks>
    <StiNet4 Condition="$(TargetFramework.StartsWith('net4'))">true</StiNet4>
    <AssemblyName>Stimulsoft.MathFX</AssemblyName>
    <RootNamespace>Stimulsoft.MathFX</RootNamespace>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>Stimulsoft.snk</AssemblyOriginatorKeyFile>
    <DelaySign>false</DelaySign>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <DebugSymbols>true</DebugSymbols>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants>TRACE;</DefineConstants>
    <DefineConstants Condition="$(Configuration.Contains('Debug'))">$(DefineConstants)DEBUG;</DefineConstants>
    <DefineConstants Condition="'$(StiNet4)' != 'true'">$(DefineConstants)NETCORE;</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="!$(DefineConstants.Contains(';DEBUG;'))">
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Fonts\*.TTF" />
    <EmbeddedResource Include="svgmath.xml" />
  </ItemGroup>
  
</Project>